# Lütkepohl 2.3

In the United States of Wonderland the growth rates of income (GNP) and the money stock (M2) as well as interest rates (IR) are related as in the following VAR(2) model:

$$
\begin{bmatrix}
    \mathrm{GNP}_t \\
    \mathrm{M2}_t \\
    \mathrm{IR}_t
\end{bmatrix} = 
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix} +
\begin{bmatrix}
    .7 & .1 & 0 \\
     0 & .4 &.1 \\
    .9 &  0 &.8
\end{bmatrix}
\begin{bmatrix}
    \mathrm{GNP}_{t-1} \\
    \mathrm{M2}_{t-1} \\
    \mathrm{IR}_{t-1}
\end{bmatrix} + 
\begin{bmatrix}
    -.2 & 0 & 0 \\
      0 & .1&.1 \\
      0 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
    \mathrm{GNP}_{t-2} \\
    \mathrm{M2}_{t-2} \\
    \mathrm{IR}_{t-2}
\end{bmatrix} + 
\begin{bmatrix}
    u_{1t} \\
    u_{2t} \\
    u_{3t}
\end{bmatrix}
$$

a) Show that the process $Y_t = (\mathrm{GDP}_t,\mathrm{M2}_t,\mathrm{IR}_t)$ is stable

**Solution**

It's necessary to show that the matrix below is invertible:

$$
\mathbf{I} - \begin{bmatrix}
    .7 & .1 & 0 \\
     0 & .4 &.1 \\
    .9 &  0 &.8
\end{bmatrix}L
\begin{bmatrix}
    \mathrm{GNP}_{t-1} \\
    \mathrm{M2}_{t-1} \\
    \mathrm{IR}_{t-1}
\end{bmatrix} - 
\begin{bmatrix}
    -.2 & 0 & 0 \\
      0 & .1&.1 \\
      0 & 0 & 0
\end{bmatrix}L^2
$$

And we can do this by verifying that the roots of the following polynomial ar *all* (in absolute values) greater than 1

$$\det\left(\mathbf{I} - \begin{bmatrix}
    .7 & .1 & 0 \\
     0 & .4 &.1 \\
    .9 &  0 &.8
\end{bmatrix}z
\begin{bmatrix}
    \mathrm{GNP}_{t-1} \\
    \mathrm{M2}_{t-1} \\
    \mathrm{IR}_{t-1}
\end{bmatrix} - 
\begin{bmatrix}
    -.2 & 0 & 0 \\
      0 & .1&.1 \\
      0 & 0 & 0
\end{bmatrix}z^2
\right)$$

Such polynomial is written as 

$$( 1 -.7z + .2z^2)(1-.4z-.1z^2)(1-.8z) + (-.1z)(-.1z-.1z^2)(-.9z)$$

Lets solve it `using Polynomials`!

In [1]:
using Polynomials

In [3]:
# Define the polynomial object
p = Polynomial([1, -.7, .2]) * Polynomial([1,-.4,-.1]) * Polynomial([1,-.8]) +
Polynomial([0, -.1]) * Polynomial([0, -.1, -.1]) * Polynomial([0, -.9])

print(p)

1.0 - 1.9*x + 1.26*x^2 - 0.323*x^3 - 0.021*x^4 + 0.016*x^5

In [5]:
# Now, we compute the roots

z = roots(p)

print(z)

ComplexF64[-5.580836123519409 + 0.0im, 1.0990151547049047 + 0.0im, 1.4503267202784422 - 1.1908225839834359im, 1.4503267202784422 + 1.1908225839834359im, 2.893667528257615 + 0.0im]

In [8]:
# Let's verify whether these roots are outside the unit circle

abs.(z) .> 1

5-element BitVector:
 1
 1
 1
 1
 1

Therefore, the process is stable (stationary)

b) Determine the mean vector of $Y_t$

**Solution**

$$Y_t = 
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix} +
\begin{bmatrix}
    .7 & .1 & 0 \\
     0 & .4 &.1 \\
    .9 &  0 &.8
\end{bmatrix}
Y_{t-1} + 
\begin{bmatrix}
    -.2 & 0 & 0 \\
      0 & .1&.1 \\
      0 & 0 & 0
\end{bmatrix}
Y_{t-2} + u_t
$$

We can take expectations on both sides. We found in a) that this process is stationary, so $\mathbb{E}[Y_t] = \mu$ for all $t$. Also, we use the fact that $\mathbb{E}[u] = 0$:

$$\mu = 
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix} +
\begin{bmatrix}
    .7 & .1 & 0 \\
     0 & .4 &.1 \\
    .9 &  0 &.8
\end{bmatrix}
\mu + 
\begin{bmatrix}
    -.2 & 0 & 0 \\
      0 & .1&.1 \\
      0 & 0 & 0
\end{bmatrix}
\mu
$$

$$
\left(
\mathbf{I} -
\begin{bmatrix}
    .7 & .1 & 0 \\
     0 & .4 &.1 \\
    .9 &  0 &.8
\end{bmatrix}-
\begin{bmatrix}
    -.2 & 0 & 0 \\
      0 & .1&.1 \\
      0 & 0 & 0
\end{bmatrix}
\right)\mu =
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix}
$$

$$
\begin{bmatrix}
    .5 & -.1 &   0 \\
     0 &  .5 & -.2 \\
   -.9 &   0 &  .2
\end{bmatrix}
\mu =
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix}
$$

$$A\mu =
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix}
$$

$$\Longrightarrow \mu = A^{-1}\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix}$$

Let's calculate $A^{-1}$ and compute $\mu$ `using LinearAlgebra`

In [10]:
using LinearAlgebra

In [12]:
A = [.5 -.1 0; 0 .5 -.2; -.9 0 .2]

3×3 Matrix{Float64}:
  0.5  -0.1   0.0
  0.0   0.5  -0.2
 -0.9   0.0   0.2

In [14]:
inv(A)

3×3 Matrix{Float64}:
  3.125   0.625   0.625
  5.625   3.125   3.125
 14.0625  2.8125  7.8125

In [17]:
μ = inv(A) * [2; 1; 0]

3-element Vector{Float64}:
  6.875
 14.375
 30.9375

c) Write the process $Y_t$ in VAR(1) form.

**Solution**

Define $y_t = \begin{bmatrix}
Y_t \\
Y_{t-1}
\end{bmatrix}$. The VAR(1) representation of $Y_t$ is

$$
y_t =
\begin{bmatrix}
    \mathbf{I}_3 \\
    \mathbf{0}_3
\end{bmatrix}
\begin{bmatrix}
    2 \\
    1 \\
    0
\end{bmatrix}+
\begin{bmatrix}
    B_1 & B_2 \\
    \mathbf{0}_3 & \mathbf{0}_3
\end{bmatrix} +
\begin{bmatrix}
    \mathbf{I}_3 \\
    \mathbf{0}_3
\end{bmatrix}u_t
$$

d) Compute the coefficient matrices $\mathbf{\phi}_1, ..., \mathbf{\phi}_5$ of the MA representation of $Y_t$. That is

$$Y_t = \mu + u_t + \sum^\infty_{k=1}\mathbf{\phi}_k u_{t-k}$$

**Solution**

We can recover $Y_t$ from $y_t$ by defining $J = \begin{bmatrix}
\mathbf{I}_3 & \mathbf{0}_3
\end{bmatrix}$ and noting that $Y_t = J y_t$. Note also that

$$
J^{'}J =
\begin{bmatrix}
    \mathbf{I}_3 \\
    \mathbf{0}_3
\end{bmatrix}
\begin{bmatrix}
    \mathbf{I}_3 & \mathbf{0}_3
\end{bmatrix} = 
\begin{bmatrix}
    \mathbf{I}_3 & \mathbf{0}_3 \\
    \mathbf{0}_3 & \mathbf{0}_3
\end{bmatrix}
$$

$$
J^{'}J\epsilon_t =
\begin{bmatrix}
    \mathbf{I}_3 & \mathbf{0}_3 \\
    \mathbf{0}_3 & \mathbf{0}_3
\end{bmatrix}
\begin{bmatrix}
    \mathbf{I}_3 \\
    \mathbf{0}_3
\end{bmatrix}u_t =
\begin{bmatrix}
    \mathbf{I}_3\mathbf{I}_3 + \mathbf{0}_3\mathbf{0}_3\\
    \mathbf{0}_3\mathbf{I}_3 + \mathbf{0}_3\mathbf{0}_3
\end{bmatrix}u_t =
\begin{bmatrix}
    \mathbf{I}_3 \\
    \mathbf{0}_3
\end{bmatrix}u_t = \epsilon_t
$$

Hence, using MA form of $y_t$

$$Y_t = Jy_t = J\left(\mathbf{I}_3 + \sum^\infty_{k=1}B^k \mathbf{b}\right) + J\epsilon_t + \sum^\infty_{k=1}JA^k\epsilon_{t-k} \\
= \mu + u_t + \sum^\infty_{k=1}JB^kJ^{'}J\epsilon_{t-k} \\
= \mu + u_t + \sum^\infty_{k=1}JB^kJ^{'}u_{t-k} \\
= \mu + u_t + \sum^\infty_{k=1}\mathbf{\phi}_ku_{t-k},
$$

with $\mathbf{\phi}_k = JB^kJ^{'}$.

Lets compute $\mathbf{\phi}_1, ..., \mathbf{\phi}_5$

In [31]:
function phi(k)
    J = [Matrix(1I, 3, 3) zeros(3,3)]
    B = [[.7 .1 0; 0 .4 .1; .9 0 .8] [-.2 0 0; 0 .1 .1; 0 0 0]; zeros(3,3) zeros(3,3)]
    return J*B^k*transpose(J)
end

phi (generic function with 1 method)

In [34]:
for k = 1:5
    print(phi(k))
end

[0.7 0.1 0.0; 0.0 0.4 0.1; 0.9 0.0 0.8][0.48999999999999994 0.11 0.010000000000000002; 0.09000000000000001 0.16000000000000003 0.12000000000000002; 1.35 0.09000000000000001 0.6400000000000001][0.3519999999999999 0.093 0.019000000000000003; 0.171 0.07300000000000002 0.11200000000000003; 1.5210000000000001 0.171 0.5210000000000001][0.2634999999999999 0.07239999999999999 0.024500000000000008; 0.22050000000000006 0.046300000000000015 0.09690000000000004; 1.5336000000000003 0.22050000000000003 0.4339000000000002][0.20649999999999993 0.05530999999999999 0.02684000000000001; 0.24156000000000008 0.04057000000000001 0.08215000000000004; 1.4640300000000002 0.24156000000000002 0.36917000000000016]